### ISSUE TITLE
Ingress for Play app

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/reactive-cli#157]
## steps

1. `sbt 'deploy minikube'`

## problem

No ingress was created.

## expectation

An ingress gets created, and it tells me where to hit.

**Comment by guizmaii** [comment]
We also hit this bug 😕

**Comment by guizmaii** [comment]
Here's a workaround until the fix is published:

```
      // Should be named "http" because of conventions in `sbt-reactive-app`
      // More info: https://developer.lightbend.com/docs/lightbend-orchestration/current/features.html#project
      //
      endpoints := HttpEndpoint(
        name = "http",
        ingress = new HttpIngress(
          ingressPorts = Vector(80, 443),
          hosts = Vector.empty,
          paths = Vector("/")
        )
      ) :: Nil
```

**Comment by alanngai** [comment]
@mitkus is this related to lightbend/reactive-app-maven-plugin#41?

**Comment by erip** [comment]
I'm not sure if this is related, but I have found that in my suite of 4 services, `bar-impl`, `baz-impl`, `foo-impl`, and `boo-impl`, all my ingress paths will resolve to the sample:

```
rp generate-marathon-configuration "my.registry.com/foo-impl" | grep -i "haproxy.*path"
    "HAPROXY_0_HTTP_BACKEND_PROXYPASS_PATH": "/api/bars",
    "HAPROXY_0_PATH": "/api/bars"
```

**Comment by TimMoore** [comment]
Unless I'm misunderstanding, this isn't a bug, but working as intended. There's no way to automatically generate an ingress configuration for a Play application (because there's no kind of metadata available to know which paths to forward) so it needs to be specified explicitly in the way @guizmaii shows in his example.

@erip Lagom services are different, because the ingress is generated from the service ACLs listed in the descriptor. If there's a bug in that, please raise it separately (but first double check that the ACLs are configured correctly).

**Comment by guizmaii** [comment]
@TimMoore ok but the situation isn't ideal because we have to know how the plugin is coded (know that we have to name `HttpEndpoint` "http") to make it works with Play.

Maybe we can propose something simpler and more robust ?

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
