### ISSUE TITLE
HttpIngress config is not being picked-up

### ISSUE THREAD

**Issue by renatocaval** [lightbend/reactive-cli#158]
See discussion on https://github.com/lightbend/sbt-reactive-app/issues/113

**Comment by mitkus** [comment]
This needs a look into the code. My gut feeling is that `ingressPorts` is not needed at all, because Endpoint.port is being used instead. Maybe it was meant for an Ingress that points to multiple services?

**Comment by renatocaval** [comment]
My intention was to open access to another port on my service. 

I have a Lagom application with an embedded akka-grpc server running alongside it. The Lagom is using the default port (10000) and I want to assign another port for the grpc one. 

The code is published here:
https://github.com/renatocaval/lagom-grpc-labs/tree/embedded-grpc-server

It turns out that it was enough for me to only declare a `HttpEndpoint`, that was all that a needed.
https://github.com/renatocaval/lagom-grpc-labs/blob/embedded-grpc-server/build.sbt#L43-L50

What I found strange is that the ingress file generated from it has no mention about the external port we want to open for it.

**Comment by renatocaval** [comment]
Maybe I'm misinterpreting it. 

We have a named port `grpc` for 8080 and the ingress config is saying, that service running on port 8080 should be exposed. And it's always exposed on port 80.

`ingressPorts` refers to the internal port to which external traffic should be forwarded, not the external port we want to open.
Is that correct?

**Comment by jsravn** [comment]
@renatocaval @mitkus asked me to take a look.

I believe kubectl always returns port `80` (or `80, 443` if TLS is defined) for `get ingress`. The external ingress port is not configurable on the resource. I'm not sure what `ingressPorts` is supposed to do here though, so I'll dig into that.

**Comment by jsravn** [comment]
I'm still not quite sure what the intention of `ingressPorts` is. From digging through reactive-cli it doesn't seem to be used. I suggest we remove that option and clarify the documentation. The only thing that can be set on an ingress resource is the `serviceName`/`servicePort`, which is configured at the endpoint level.

**Comment by eed3si9n** [comment]
I think `ingressPorts` is a vestige of the ConductR past called TCP based request ACLs.
http://conductr.lightbend.com/docs/2.0.x/AclConfiguration#Declaring-TCP-based-request-ACLs

> In the example above, the TCP port `3303` and `12101` will be exposed via the proxy and the requests to these ports will be relayed to the endpoint.

Another evidence for this is https://github.com/lightbend/sbt-reactive-app/pull/11 where `trait Ingress` was first declared with `def ingressPorts: Seq[Int]` as a replacement of `trait Acl`. It says:

> - `PortIngress` - indicates a service should be available from the ingress controller on the specified port. I think for now we can drop these on the CLI side (perhaps `log.warn`) but I think they can be implemented by creating a LoadBalancer or configuring the NGINX ingress controller in a particular manner.

### Ingress resource

Legitimate Ingress resource does NOT support "L4" TCP traffic (because there's  Service resource with `type: LoadBalancer`?). However, various Ingress controllers have added their own something to workaround this:
- haproxy-ingress [tcp-services-configmap](https://github.com/jcmoraisjr/haproxy-ingress#tcp-services-configmap)
- ingress-nginx - [Exposing TCP and UDP services](https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/exposing-tcp-udp-services.md)
- IBM Cloud Kubernetes Service - [tcp-ports](https://console.bluemix.net/docs/containers/cs_annotations.html#tcp-ports)

### Service resource

OpenShift uses LoadBalancer Service by allowing an ingress IP address to be set to a Service - [Configuring the Cluster to Use Unique External IPs](https://docs.openshift.com/container-platform/3.11/admin_guide/tcp_ingress_external_ports.html#unique-external-ips-ingress-traffic-configure-cluster).

Google Cloud also uses `LoadBalancer` - [Service](https://cloud.google.com/kubernetes-engine/docs/concepts/service):

> When you create a Service of type `LoadBalancer`, a Google Cloud controller wakes up and configures a network load balancer in your project. The load balancer has a stable IP address that is accessible from outside of your project.

### Back to HttpEndpoint

So it looks like L4 load balancing is a thing, but it probably doesn't make sense for `HttpEndpoint` to have ingressPorts.

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
