### ISSUE TITLE
"Failed to obtain Docker config" on Bintray-hosted registry

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/reactive-cli#175]
Originally reported by @mjcramer

## steps

```
docker login -u user -p **** org-foo-registry.bintray.io
rp generate-kubernetes-resources --generate-all "org-foo-registry.bintray.io/org/play-openshift-example:0.10"
```

## problem

```
[error, com.lightbend.rp.reactivecli.Main$] Failed to obtain Docker config for org-foo-registry.bintray.io/org/play-openshift-example:0.10, unable to access repository or registry; check authentication [401]
```

## expectation

YAML gets generated.

**Comment by TimMoore** [comment]
@eed3si9n I see #176 was merged. Does that mean this is fixed or is there still another issue?

**Comment by ikamman** [comment]
Please look at https://github.com/lightbend/reactive-cli/pull/178 this may solve your problems.

**Comment by cs4inctec** [comment]
Hello, our team recently began using lagom, and we are now trying how to deploy the services. 

Using minikube we get this error by
- Following the [documentation](https://developer.lightbend.com/docs/lightbend-orchestration/current/getting-started/sbt-play-minikube.html) on out code, and
- also while trying the [auction-demo](https://github.com/lagom/online-auction-scala); with the only change being an updated sbt-reactive-app plugin (1.7.0).

There is also a recent [thread](https://discuss.lightbend.com/t/possible-reactive-app-bug-minimum-sbt-reactive-app-version-is-1-7-0-docker-image-was-built-using-1-6-1/3395/2), where a downgrade to 1.6.1 "fixed" this issue. Unfortunately I am unable to try this, due to not knowing how to downgrade reactive-cli on mac using homebrew :(
