### ISSUE TITLE
Direct libcurl binding

### ISSUE THREAD

**Issue by longshorej** [lightbend/reactive-cli#79]
Instead of having a libhttpsimple subproject, can we directly bind to the curl libraries? The main issue here is the usage of C macros. It's not clear how to call the functions from Scala Native.

See:

https://github.com/fsat/scala-native-libcurl-bindings
https://github.com/fsat/scala-native-typedef-enum-bindings

**Comment by mitkus** [comment]
The previous approach didn't work because these constants don't end up in native libraries anywhere - they exist only inside C preprocessor. `!DIEnumerator` entry in the compiler explorer is debug info only, it's not present in the shipped libraries and I doubt scala-native looks at it anyway.

I'm doing a little experiment with jcpp (https://www.anarres.org/projects/jcpp/), I think we can generate bindings for libcurl from the curl.h header. In general it should be possible to automatically generate bindings for any native library this way, but narrowing the focus down to only libcurl numeric constants (#defines & enums) makes the problem much simpler.

**Comment by mitkus** [comment]
I have direct binding functioning now: https://github.com/lightbend/reactive-cli/pull/83

What remains is to do some more testing, code cleanup, and try out if release process still works.

**Comment by longshorej** [comment]
Fixed via #83
