### ISSUE TITLE
Consider publishing logic as a lib

### ISSUE THREAD

**Issue by longshorej** [lightbend/reactive-cli#93]
Once #89 is in, we could publish the shared code as a library. sbt-reactive-app could depend on it, thus allowing resources to be generated from SBT without installing the CLI. Flexibility/convenience thing.

We could take it a step further and add a command to SBT that for each project, builds images, generates resources, and pipes them to `kubectl apply`. Useful for local development, similar to ConductR's `sbt install`.

**Comment by dwijnand** [comment]
@mitkus (or @longshorej) could you help me understand which parts of the codebase this refers to? And any other details I would benefit from knowing in order to do this. Thanks!

**Comment by longshorej** [comment]
I don't think this is strictly necessary anymore, but the idea here was to publish the logic of the CLI as a library -- i.e. the part that parses the Docker labels and spits out Kubernetes YAML.

`sbt-reactive-app` (and its maven counterpart) would then depend on said library and invoke it directly for its `deploy minikube` functionality, instead of requiring the user to install the CLI.

Operators would still need the CLI installed on a jump server or bastion host or whatever, so the CLI would still need to exist as well as a mechanism to grab the labels from the registry and feed them to this library.

Hope that gives enough info to make a decision. I feel like installing the CLI isn't that difficult though with the repositories available, and feel that this can be closed.

**Comment by pmcjury** [comment]
This would also be a good use case for building custom tooling. For example, a developer could use the lib to build their own "custom-rp". I would like to do this in order to follow a more declarative approach to k8s manifest management using helm. I want to use "rp" conventions to output a helm template that mimics the logic in the generators in this lib. You would only need to do this once, or download the template from this repo. "custom-rp" will generate my values.yaml file, containing the "rp" specific values for rendering the helm template. I could then extend the template, and apply other values as per my deployment setup.

This would also help with custom resource generation in k8s which is not supported by rp as is. An example would be the usage of a service mesh like istio , where k8s native Ingress is not used , but CRDs called Gateways and VirtualServices.

Example:

```
# init one time only manually
custom-rp generate-kubernetes-helm-chart "some-project/svc-impl:1.0.0-SNAPSHOT"
...created chart/svc-impl

# subsequent iterative CI/CD
custom-rp  generate-kubernetes-helm-values "some-project/svc-impl:1.0.0-SNAPSHOT"
...created rpValues.yaml

helm deploy chart/svc-impl -f rpValues.yaml -f rpCustomOverridesValues.yaml
```

**Comment by TimMoore** [comment]
Lightbend Orchestration is no longer actively developed and will reach its [End of Life](https://developer.lightbend.com/docs/lightbend-platform/2.0/support-terminology/index.html#end-of-life-eol-) on April 15, 2020.

We recommend [Migrating to the Improved Kubernetes Deployment Experience](https://developer.lightbend.com/docs/lightbend-orchestration/current/migration.html).
